### ISSUE TITLE
[bmrg-auth-proxy] Basic Auth - Incorrect redirection after sign in

### ISSUE THREAD

**Issue by aiciobanu** [boomerang-io/charts#26]
**Describe the bug**
The user is redirected to `/` instead of the home path parameter set for that application

**To Reproduce**
1. Deploy `bmrg-auth-proxy` chart version 3.3.1 using basic auth
2. Deploy an application that is integrated with auth-proxy
3. Sign in

**Expected behavior**
The user should be redirected to the `sign_in` `rd` parameter instead of `/`

**Screenshots**
N/A

**Environment (please complete the following information):**

- OS: macOS
- Browser: firefox
- Version: 83.0

**Additional context**
N/A

**Comment by morarucostel** [comment]
Closed, with the release of chart version 3.2.2
