### ISSUE TITLE
Helm chart incorrect references eventing.nats. instead of eventing.jetstream

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/charts#50]
**Describe the bug**
Helm chart may have incorrect references eventing.nats. instead of eventing.jetstream

**To Reproduce**

1. Look at the configmap in the Flow chart

**Screenshots**
![image](https://user-images.githubusercontent.com/16438811/145878662-20585ee9-5e9e-4512-b889-f2c7a95b5c9d.png)

**Comment by tlawrie** [comment]
It may correct but not entirely sure.

**Comment by corcoja** [comment]
Hey @tlawrie, I've split eventing-related properties into two sub-categories:
1. `eventing.nats.*` – these are properties for the NATS server itself, things like the URL/URLs of the server/servers, reconnect time, maximum reconnect attempts, etc.
2. `eventing.jetstream.*` – Jetstream related properties (independent of the NATS server properties). Through these you can configure the Streams and Consumers used by the services.

I'm open to suggestions to use a different naming scheme 🙂

**Comment by tlawrie** [comment]
Ah. Makes sense. 

Typically in the past we have made sure to reference everything with the same prefix. i think that's fine here as the helm chart values.yaml is still trying to achieve that and make it easier for the end user, its only in the configmap.
