### ISSUE TITLE
NGINX Ingress Controller 0.32.0

### ISSUE THREAD

**Issue by 51qzpw** [boomerang-io/charts#51]
`error message` :  could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
nginx: [warn] could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
2022/01/07 03:22:23 [warn] 967#967: could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
nginx: [warn] could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
2022/01/07 03:22:23 [emerg] 967#967: "proxy_cache" zone "authentication" is unknown in /tmp/nginx-cfg218567592:1259
nginx: [emerg] "proxy_cache" zone "authentication" is unknown in /tmp/nginx-cfg218567592:1259
nginx: configuration file /tmp/nginx-cfg218567592 test failed

I want to know which nginx-ingress-cotroller version can be installed successfully? 
My environment:
kubernetes: v1.19.16
helm: 3.5.4
nginx-ingress-controller: 0.32.0

**Comment by tlawrie** [comment]
Assigning to @morarucostel

**Comment by morarucostel** [comment]
Hi @51qzpw , 
We use the nginx ingress controller 1.2.0 if you wanna give it a try. 
Here is an article on how to install Flow on a local machine, which lists also the versions that are installed.
https://itnext.io/lets-put-boomerang-flow-on-our-laptop-8a63eac2b9e5

In step 3, it describes how to install nginx and what to run. 
It uses the `k8s.gcr.io/ingress-nginx/controller:v1.2.0` image.

**Comment by morarucostel** [comment]
Closing the issue due to inactivity.
